set number
set nowrap
set showmatch

set hlsearch
set ignorecase
set smartcase
set incsearch

set noexpandtab
set smarttab
set shiftwidth=4
set tabstop=4
set softtabstop=4

set autowrite
set autochdir

set modeline

set undolevels=1000
set backspace=indent,eol,start

set lazyredraw

set nobackup
set noswapfile
set writebackup

syntax enable

if has('unnamedplus')
	set clipboard=unnamedplus
else
	set clipboard=unnamed
endif

if has("mouse")
	set mouse=a
endif

" xdg directory spec
if empty($XDG_CONFIG_HOME)
	let $XDG_CONFIG_HOME="$HOME/.config"
endif
if empty($XDG_CACHE_HOME)
	let $XDG_CACHE_HOME="$HOME/.cache"
endif
set directory=$XDG_CACHE_HOME/vim/swap,/var/tmp,/tmp
set backupdir=$XDG_CACHE_HOME/vim/backup,/tmp
set undodir=$XDG_CACHE_HOME/vim/undo
set viminfo+=n$XDG_CACHE_HOME/vim/info
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

map <c-n> :tabn<CR>
map <c-t> :Te<CR>
map <c-f> :Ex<CR>

autocmd Filetype python setl expandtab
autocmd Filetype yaml setl expandtab shiftwidth=2 tabstop=2 softtabstop=2
autocmd BufRead,BufNewFile *.md set filetype=markdown

" vundle init
filetype off
set shell=/bin/bash

set runtimepath+=$XDG_DATA_HOME/vim/bundle/Vundle.vim
call vundle#begin("$XDG_DATA_HOME/vim/bundle")

Plugin 'gmarik/Vundle.vim'

" lanugages & formats
Plugin 'dag/vim-fish'
autocmd FileType fish compiler fish
autocmd FileType fish setlocal textwidth=79
autocmd FileType fish setlocal foldmethod=expr
Plugin 'fatih/vim-go'
let g:go_disable_autoinstall = 1
Plugin 'chase/vim-ansible-yaml'
Plugin 'pangloss/vim-javascript'
Plugin 'kchmck/vim-coffee-script'
Plugin 'leshill/vim-json'
Plugin 'othree/html5.vim'
Plugin 'indenthtml.vim'
Plugin 'mutewinter/nginx.vim'
Plugin 'rhysd/vim-clang-format'
let g:clang_format#code_style = 'file'
let g:clang_format#detect_style_file = 1
let g:clang_format#auto_format = 1
let g:clang_format#auto_format_on_insert_leave = 1
let g:clang_format#auto_formatexpr = 1
Plugin 'nvie/vim-flake8'

" navigation
Plugin 'tpope/vim-rsi'
Plugin 'tpope/vim-unimpaired'

" utilities
Plugin 'itchyny/lightline.vim'
set laststatus=2
Plugin 'Valloric/YouCompleteMe'
Plugin 'rking/ag.vim'
Plugin 'majutsushi/tagbar'
nmap <F6> :TagbarToggle<CR>
Plugin 'tpope/vim-surround'

" vundle end
call vundle#end()
filetype plugin indent on
