#!/usr/bin/osascript
set musicApps to {"com.spotify.client", "com.apple.iTunes"}

do shell script "echo " & quoted form of (getTrackInfo from musicApps)

to getTrackInfo from musicAppList
	repeat with musicApp in musicAppList
		using terms from application "iTunes"
			try
				tell application id musicApp
					if it is running and player state is playing then
						set track_name to name of current track
						set artist_name to artist of current track
						return ("♪ " & track_name & " (" & artist_name & ") | ")
					end if
				end tell
			end try
		end using terms from
	end repeat
	return ""
end getTrackInfo
