#!/bin/bash

set -e
set -u

id=$(youtube-dl --get-id $1)

mkdir -p "/tmp/${id}"

youtube-dl -f 137 -o "/tmp/${id}/v.mp4" $1
if [[ $? -ne 0 ]]; then
	exit $?
fi

youtube-dl -f 139 -o "/tmp/${id}/a.m4a" $1
if [[ $? -ne 0 ]]; then
	exit $?
fi

ffmpeg -i "/tmp/${id}/v.mp4" -i "/tmp/${id}/a.m4a" -c:v copy -c:a copy "${id}.mp4"
if [[ $? -ne 0 ]]; then
	exit $?
else
	rm -r "/tmp/${id}"
fi
