#!/bin/bash

id=$(youtube-dl --get-id $1)
youtube-dl -f 137 -o "/tmp/${id}-v.mp4" $1
youtube-dl -f 139 -o "/tmp/${id}-a.m4a" $1
ffmpeg -i "/tmp/${id}-v.mp4" -i "/tmp/${id}-a.m4a" -c:v copy -c:a copy "${id}.mp4"
