#!/bin/bash

set -e
set -u

if [ $# -ne 1 ]; then
	echo "Usage: $(basename "${0}") <project>"
	exit 1
fi

mkdir -p "${1}"/{,src,pkg,bin}

cat << 'EOF' > "${1}/activate"
if [ -z "$BASH_VERSION" ]; then
	export GOPATH="$(cd "$(dirname "${0}" )" && pwd)"
else
	export GOPATH="$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"
fi
export OLDPS1=$PS1
export PS1="[go:$(basename $GOPATH)] $PS1"
alias gcd="cd $GOPATH"
deactivate() {
	export PS1=$OLDPS1
	unset GOPATH
	unset OLDPS1
	unalias gcd
	unset deactivate
}
EOF

cat << 'EOF' > "${1}/activate.fish"
set -x GOPATH (dirname (status -f))
functions -e __genv_fish_prompt
functions -c fish_prompt __genv_fish_prompt
functions -e fish_prompt
function fish_prompt
	printf "[go:%s] %s" (basename $GOPATH) (__genv_fish_prompt)
end
function gcd
    cd $GOPATH
end
function deactivate
    set -e GOPATH
	functions -e fish_prompt
	. ( begin
		printf "function fish_prompt\n\t#"
		functions __genv_fish_prompt
	end | psub )
	functions -e __genv_fish_prompt
	functions -e deactivate
end
EOF

cat << 'EOF' > "${1}/$(basename "${1}").sublime-project"
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings": {
		"GoSublime": {
			"env": {
				"GOPATH": "$PWD"
			}
		}
	}
}
EOF
