#!/usr/bin/env bash
set -e -u

binexists() {
	type -t ${1} >/dev/null
}

check-prereqs() {
	if ! binexists youtube-dl; then
		echo >&2 'youtube-dl not found'
	fi
}

channel=${1}
if [[ $( uname -s ) = Darwin ]]; then
	open='open -a "QuickTime Player"'
elif [[ $( uname -s ) = Linux ]]; then
	open='mpv'
fi

youtube-dl -g "http://twitch.tv/${channel}" | xargs "${open}"
